### ISSUE TITLE
prepareOutput

### ISSUE THREAD

**Issue by DKoenig9** [lenneTech/nest-server#123]
When i update an item and return the createdAt-attribute, i get null as value. I fixed this by just returning the mappedItem without the prepareOutput-method.

**Comment by kaihaase** [comment]
Hello @DKoenig9,

Dates should not be converted to null by `pepareOutput` in the current version (8.5.0). Please check if it works and let me know if the bug still exists or if everything is working now. So that I can continue to work on the issue or close it.
